### ISSUE TITLE
Name proposals for the organization

### ISSUE THREAD

**Issue by chrisplatorres** [M3-org/proposals#1]
Submit name ideas here

Post one name per comment, and then upvote or downvote the names you like / dislike.

**Comment by chrisplatorres** [comment]
Some name ideas from meetup..
Open Metaverse Gathering
Open Metaverse Mafia
Open Metaverse Gang

**Comment by rzr** [comment]
my proposal was "XrHub"

as lazy typer, I prefer small names  ;)

ps: @chrisplatorres may you add one comment per proposal , and then invite user to vote +1 on each ?

**Comment by chrisplatorres** [comment]
Good idea @rzr , let's make one name per comment so people can upvote the names they like.

one name: Open Metaverse Gathering

**Comment by modulesio** [comment]
I like the fact that MMM is WWW upside down.
Metaverse Makers Mafia
Open Metaverse Gang

**Comment by chrisplatorres** [comment]
Open Metaverse Mafia

**Comment by chrisplatorres** [comment]
Open Metaverse Gang

**Comment by SpaceHexagon** [comment]
Open World Builders (group)

**Comment by rzr** [comment]
@modulesio  if you like names, just add +1 on the one you like, or add new ones if not yet listed

"invalid" comments / proposals will get -1 to avoid confusion

**Comment by SpaceHexagon** [comment]
Cyber-Civil Engineering meetup

**Comment by SpaceHexagon** [comment]
@rzr  isn't it more like a purgatory?  😄

**Comment by modulesio** [comment]
Open Metaverse Gathering

**Comment by nnnnicholas** [comment]
Metaverse Gang 🚨

**Comment by madjin** [comment]
> Metaverse Gang

+1 It's short, rolls off the tongue nicely, and has a nice sound that will go well with some sick beats. Think it fits well for a group of associates bound by principles of an open and decentralized metaverse.

**Comment by madjin** [comment]
Spatial Web Friends

**Comment by madjin** [comment]
> I like the fact that MMM is WWW upside down.
> 
> Metaverse Makers Mafia

Continuing with the MMM trend:

Metaverse Makers Meetup

**Comment by modulesio** [comment]
Open Metaverse Group

If we're looking to be more official. 🕴

**Comment by modulesio** [comment]
Embodied Computing Club (EC2)

**Comment by madjin** [comment]
Metaverse Mafia

If you recall in Snow Crash, Hiro was working for the Mafia delivering pizza. We can also dress up in black tie attire every time we meetup in virtual worlds (which Hubs has plenty of defaults for).

**Comment by nnnnicholas** [comment]
To choose a good name we need to know the group's purpose. What brings us together? (@kentbye)

From what I heard tonight, the group consists of _people who want to accelerate open XR development_ (@modulesio). We're people living in this medium who say "hey, why can't this future be more like the web and less like a proprietary platform, whether it's called a 'browser' or not." 

Someone mentioned that their main goal is to bring more people into the Open XR fold. We left undefined whether that means more "users" or active makers. To me, there are lots of trillion dollar companies trying to popularize XR in general. While we haven't nailed down a specific shared definition of "open," it is somehow in contrast to these "closed" systems. 

Open XR is perhaps uniquely incentivized to make it easy for users to become creators, without forcing them to invest their attention into proprietary tools. Proprietary XR platform companies may say they want to empower users to "create", but they are broadly incentivized to limit XR authorship to tools that they control so that they can build monopolistic moats around software distribution, and eventually derive revenues from captured devs and users (Thiel, Jobs, Zuckerberg, Unity). 

What makes this group special is that the talent is in the room. Between us are people making the engine, the applications, and thinking in public about what it all means. We have the chops to 1) share empowering knowledge through tech talks/tutorials, 2) create tight feedback loop between applications and engine builders, 3) build/demo/iterate/collaborate with other passionate makers.

I think it would be a shame to make yet another group of people saying "yay immersive media!" It's too bland. I want something with teeth. A place where friendly competition and informal knowledge sharing inspires awesome projects you just won't find outside of Open XR. Hubs is a great example.

As I said in the meeting : cool bands don't call themselves "Music" or "Rhythm." If it's a group of people with skills to make stuff, then the work makes the name meaningful. I think it should have some character. I am most excited thinking of this group like the sickest skatepark in town. It's a place to do tricks, push each other forward, and simultaneously inform infrastructure development. To me, we're like skaters busting tricks for our friends, the people who _get it_. It's more humble and real than a metaverse. It's what we did tonight. 

I partly think we can do better than the same old sci-fi language that, while cool in one way, is already deeply colonized by the "hey look we're hip" corporate interests. (Neal Stephenson, Chief Futurist at Magic Leap). 

Of the ones we've said my favorites are Metaverse Gang or Cyber-Civil Engineering Group (not precisely this phrasing but it sounds so different from what I normally hear that I am drawn to it). I'm definitely open to other ideas that stray further from the typical marketing speak. That said I think this convo has already been productive for establishing our positions together, regardless the specific outcome !

My 2¢ 💸 :)

**Comment by blairmacintyre** [comment]
Dumb question:  when folks are saying "Open XR" they mean "XR that is Open", not the Khronos standard, right?  

(and I'm sorry I didn't join the meetup, I didn't know it was happening, how does one get notified?)

(and I really like the MMM idea, I upvoted one of those)

**Comment by rzr** [comment]
@blairmacintyre 
Yea **OpenXR** is already owned by Khronos  no need to add confusion to use this or derivates.

**Comment by AlbertoElias** [comment]
Hey! Sorry I missed the meetup, it wasn't at a great time for folks in other timezones.

Regarding the name, I think we should avoid things like mafia or gang, they don't feel as accessible and feel more like a "boys club". I upvoted some of the others which sound pretty good

**Comment by modulesio** [comment]
@nnnnicholas Thank you for the thoughtful dive into the "why" of the group -- my feelings are mostly aligned.

"Open" to something very specific. There is a lot of money invested into building and promoting XR moats -- and certainly there are people in these conversations who are paid to benefit their parent company and that's ok.

But a metaverse _cannot_ be built by companies incentivized to exclude and block approaches that are contrary to their business structure.

What makes XR different is -- and this was brought up in the meetup -- is that XR is a technology defined by closer and closer vergence with _actual reality_.

I don't think there's many people who _want_ their reality to become a battleground for businesses, or for it to be monopolized by a single entity. You don't need to dig very deep in the SF bookshelf for ideas on why that won't work.

And I think the elephant in the room is that the final form of XR is a several hills away, so there are still many opportunities to discover where we each want to fit in, and where the real value for our work comes from.

I talk to a lot of people who are making amazing things, and it's equally amazing how often their idea and passion is stifled from becoming a reality and they give up.

Some of it is technological, some of it is corporate, and some of it is social. So you have all of these little sparks where people have made an awesome ingredient for a metaverse, but it has a hard time igniting because someone said no, someone set up a roadblock, or maybe we were just too self-interested and shortsighted to help each other win together, and decided instead to compete ourselves into a standstill.

The reason I think "makers" is a better focus for the name than "users" is that I don't think end users care about openness. Users dream about a metaverse, and a lot of people promise it, but most people only care whether it becomes a reality -- not who made it.

Of course, we probably want to spread these ideas to welcoming ears, but the missing ingredient is the collaboration of makers who build this mountain rather than dreaming about it. This requires a collaboration between people from all parts of the stack and idea space -- whether you are hacking hardware, engines, browsers, specs, models, worlds, sites. I'm hesitant to call it strictly "Web", or any term that is easy to monopolize into very communication problem that we are trying to solve.

> Dumb question: when folks are saying "Open XR" they mean "XR that is Open", not the Khronos standard, right?

Correct.

**Comment by chrisplatorres** [comment]
@blairmacintyre We will also be notifying through twitter (https://twitter.com/exokitXR) and posting dates beforehand on the GitHub repo.

**Comment by smsithlord** [comment]
Spatialized Metaverse Guild
Being somebody who believes the metaverse exists even if we don't visualize it any particular way, I like Spatialized Metaverse and then Guild because it seems fun & game related. :)

**Comment by blairmacintyre** [comment]
@smsithlord I'm going to reiterate what @AlbertoElias said above;  game and nerd terms will send a message that only a certain subset of folks are welcome.  

I play games, am somewhat of a nerd, but even for me Guild is offputting, since I never got into WoW or any of the games that I associate with "Guild" ... similar reaction to "Gang", "Club", etc.  

I like Group and Meetup.  I also kind of like "Gathering", esp if there will be an emphasis on meeting in XR, as it feels like a "provocative variation on Meetup" ...

**Comment by weddingdj** [comment]
Immersive Web Meetup

**Comment by seacloud9** [comment]
XR the Gathering

**Comment by smsithlord** [comment]
@blairmacintyre I've never played WoW or any game that called groups guilds either. :D  I just think something fun sounding over something boring sounding.  And Guild is something a lot of people see as fun.

**Comment by blairmacintyre** [comment]
@smsithlord I don't disagree that Guild sounds fun for many people.  My point is that if you want all the people who might have interesting things to contribute to come, you probably want to avoid picking names that will be a turn-off to a lot of people.

You may not.  Perhaps the intent is to have this be a group aimed more at gamers and fantasy nerds (that's not meant as pejorative -- I'm a gamer and fantasy nerd).  But, then I don't see the point of creating it, because it will be a pretty insular discussion.

I wouldn't bother coming to something named Guild or Gang because those turn me off;  I wouldn't be inclined to come because time is limited, and I'd rather join things that have a broader membership.  I get plenty of time chatting with gamers when I play Overwatch. ;)

**Comment by chrisplatorres** [comment]
Open Metaverse Gathering and Metaverse Makers Meetup are in the lead for name. We should decide on the name before the next meetup: Thursday May 2nd. ( was agreed during previous meetup that bi-weekly was a good pace )

**Comment by cmdrflexo** [comment]
one quick question: is this where i can find WASM armor-clad weirdos?

**Comment by smsithlord** [comment]
@blairmacintyre not a fantasy nerd myself either heh, more of a scifi guy, but I get that you think Guild is going to put off a lot of people.  I'll take your input, as it didn't go over well with you certainly. :D  Just throwing in my 2 cents.

**Comment by chrisplatorres** [comment]
![metaversemakersmeetupCapture](https://user-images.githubusercontent.com/29695350/57009185-c1249500-6bba-11e9-87c7-da0823fba1d5.PNG)
![gathering1Capture](https://user-images.githubusercontent.com/29695350/57009186-c1249500-6bba-11e9-82cd-cfea240560bb.PNG)

It looks like Metaverse Makers Meetup is winning by 1 vote, Open Metaverse Gathering being a close 2nd. Let's decide on using whatever name is most upvoted by the end of today (Wednesday).

Tomorrow, Thursday May 2nd there will be another meetup. Please comment what time works best for you in the issue here: https://github.com/open-metaverse-gathering/proposals/issues/3

**Comment by rzr** [comment]
I like the MMM one too but words Makers and Meetup are somehow owned by other communities, so I voted for the 1st OMG proposal (which is ahead now)  because there was one more for OMG see https://github.com/open-metaverse-gathering/proposals/issues/1#issuecomment-484749980

**Comment by modulesio** [comment]
It seems there's no strong consensus to change it from the original name (Open Metaverse Gathering), which was not controversial or loaded. Let's keep it at that.

**Comment by chrisplatorres** [comment]
[Updated schedule here](https://github.com/open-metaverse-gathering/schedule/blob/master/README.md) for the Thursday May 2nd meet. We will go over the comments here and address the org naming.

**Comment by chrisplatorres** [comment]
At the past meetup we agreed on the name "m3" or "M3" for the organization. Since the name is currently occupied by an unused account, @modulesio contact GitHub about using the name for the org.

**Comment by vyrnix9582046173** [comment]
We were not able to get the "M3" org name from GitHub, so the org name on GitHub is `M3-org`, which is the next closest thing to "M3".

**Comment by rzr** [comment]
I assume this ticket can be closed now ?
